Update all raised ``Exceptions`` to inherit from a ``PyGethException``
